title: testCourse
description: This is a test course just to see what is available to me.
template:
  repo: testcourse-template
  name: testcourse
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
